### ISSUE TITLE
about clone directory

### ISSUE THREAD

**Issue by UltraHertzz** [ika-rwth-aachen/docker-ros#17]
Hi,
In section "build image locally", i was confused about the ros rpository. Does that mean my ros installation directory or my workspace? or docker installation directory

**Comment by lreiher** [comment]
Using docker-ros, you can containerize any ROS package or set of packages. The *ros repository* refers to a directory containing the source code for the packages you wish to containerize. Usually this is a Git repository, hence the term *repository*, but it doesn't need to be.

If you wish to containerize an entire ROS workspace, the *ros repository* would refer to your `ws/src` directory that is containing all of your packages.

**Comment by UltraHertzz** [comment]
ok gotcha, thx
